version: '3'
services:
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - 'database-net'
    volumes:
      - ./data:/var/lib/mysql
  app:
    build: ./
    ports:
      - '8080:8080'
networks:
  database-net:

