name: Create envfile

on: [ push ]

jobs:
  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_HOST: ${{ secrets.HOST }}
          envkey_DB_USERNAME: ${{ secrets.DB_USERNAME }}
          envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          envkey_DATABASE: ${{ secrets.DATABASE }}
          envkey_DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          directory: <directory_name>
          file_name: .env
          fail_on_empty: false
          
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pull-test-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTVM }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd app
            git pull origin main
            go test -v ./..
            docker-compose down && docker-compose up --build -d